### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by MK85Pilot** [clauadv/cs2_webradar#10]
Will wss be updated? I think security will improve quite a bit. Already star, cool release

**Comment by clauadv** [comment]
what do you mean? like to kick unwanted guests from the web socket?

**Comment by MK85Pilot** [comment]
No, I mean ws(websocket) traffic is not encrypted, anyone or anti-cheats can get the packets, why not use wss, using ssl to protect the data sent, when sharing cheats

**Comment by clauadv** [comment]
oh. yea, sounds good although VAC doesn't care about any of that but yea, for faceit that should be a good measure

**Comment by xPh03n1x** [comment]
**You can close this and disregard completely.**

Here's the long explanation to "why this ain't needed or even necessary".

First and foremost, adding a certificate layer on a WebSocket does only one thing - it creates SSL verification to be used when establishing a connection, not on exchanging data. WS is UDP, it is not TCP - whoever believes UDP can be protected by an SSL needs to read more on what UDP is and how it works.

This is supposed to be ran locally, working with either `localhost` or a local IP address - you cannot have SSL on either of them. You can use "self signed" certificate, but that has the security of "no SSL" anyway. Yes, you can do "public access" and you can get an SSL if you have a domain but ... why not just use CloudFlare's free service, which will add a secure layer on your insecure back-end connection anyway?

Furthermore, the operational logic here is:

CS2 -> Usermode - [WS] -> User

Anti-cheat software does not care what packets a suspicious process is sending out via any communication method - it will care what data is using/modifying of the priority process (CS2 in this case).

In the end, if you spend the time to work and implement SSL logic (which comes with verifications and things like that, it ain't just about "WSS support") it will be just a waste - it won't help anyone/anything.

**Comment by huntergregal** [comment]
> **You can close this and disregard completely.**
> 
> Here's the long explanation to "why this ain't needed or even necessary".
> 
> First and foremost, adding a certificate layer on a WebSocket does only one thing - it creates SSL verification to be used when establishing a connection, not on exchanging data. WS is UDP, it is not TCP - whoever believes UDP can be protected by an SSL needs to read more on what UDP is and how it works.
> 
> This is supposed to be ran locally, working with either `localhost` or a local IP address - you cannot have SSL on either of them. You can use "self signed" certificate, but that has the security of "no SSL" anyway. Yes, you can do "public access" and you can get an SSL if you have a domain but ... why not just use CloudFlare's free service, which will add a secure layer on your insecure back-end connection anyway?
> 
> Furthermore, the operational logic here is:
> 
> CS2 -> Usermode - [WS] -> User
> 
> Anti-cheat software does not care what packets a suspicious process is sending out via any communication method - it will care what data is using/modifying of the priority process (CS2 in this case).
> 
> In the end, if you spend the time to work and implement SSL logic (which comes with verifications and things like that, it ain't just about "WSS support") it will be just a waste - it won't help anyone/anything.

there is a lot wrong here...

but first and foremost - websockets use tcp not udp. WSS (secure websockets) are encrypted and provide a much higher level of protection.

Self signed  certs are not just as good as using no certs.... the data is encrypted when using self signed certs. It makes is significantly harder for an AC to inspect the data. 

You don't need a domain to use ssl. you can easily used a self signed cert to enable https/ssl encryption without a domain.

Currently - VAC does not check network connections. But other anticheats DO - so future proofing your cheat is wise.

**Comment by xPh03n1x** [comment]
> but first and foremost - websockets use tcp not udp. WSS (secure websockets) are encrypted and provide a much higher level of protection.

The initial connection is TCP. Once the connection is established, there's nothing TCP about it. Want some proof? Establish a WSS connection between two peers and use software (like Wireshark) to capture and read the packets. If you are observing the network layers (if you are familiar with the OSI model), you will every quickly note that the "TCP connection" you established is remarkably operating in a very UDP manner.

> Self signed certs are not just as good as using no certs.... the data is encrypted when using self signed certs. It makes is significantly harder for an AC to inspect the data.

Yes, they are. When Peer A says "here is my certificate, you can't use anything to verify it with", then Peer B has to just "take their word for it". With any Man-in-the-middle attack, the attacker just uses their own self-signed certificate and says the same - Peer B has absolutely no way of knowing that this isn't the certificate used by Peer A.

Harder? Yes, I'll give you that, it is harder. However, it is as harder as having to open your bottle of water before drinking from it, compared to directly drinking from an already opened bottle of water. Ultimately, it doesn't even compare to a bottle of water placed in a locked safe box - that's what I'd call "harder".


> You don't need a domain to use ssl. you can easily used a self signed cert to enable https/ssl encryption without a domain.

^ Read above


> Currently - VAC does not check network connections. But other anticheats DO - so future proofing your cheat is wise.

Right, and currently humans do not fly, but other mammals do. So by the same logic going out tomorow for grocery shopping with a parachute is "wise" - 🤡



> there is a lot wrong here...

If you are going to say something is wrong, you should be able to back the statement with a proof. Backing it with an opinion doesn't disproof the statement. If you don't know this - even your opinion is not worth anyone's time.



I am not interested in debating this. I said what I said. Everything listed in this, and in my previous message, can be very easily verified for less than 30 minutes reading on the subjects. What you do with your own time is on you, I got better things to do with mine than spend it educating random people on the Internet.
