### ISSUE TITLE
failed to attach to cs2.exe

### ISSUE THREAD

**Issue by BaLaLaLs** [clauadv/cs2_webradar#12]
The following error occurred when I compiled and ran usermode
![image](https://github.com/clauadv/cs2_webradar/assets/23353559/3743d3f6-1900-43b8-9af1-aee6484aad09)

**Comment by clauadv** [comment]
you need to run it as admin

**Comment by BaLaLaLs** [comment]
I still cannot achieve the expected results when running a powershell with admin
![image](https://github.com/clauadv/cs2_webradar/assets/23353559/441d1f78-7675-4eb8-821e-31ecb5f6b674)

**Comment by clauadv** [comment]
do you have any anticheat running?

**Comment by BaLaLaLs** [comment]
I haven't run any anti cheating software.

**Comment by clauadv** [comment]
i have no idea, looks like you cant read memory at all. i've added some errors logs for 'attach' function. try to redownload the project and compile again

**Comment by BaLaLaLs** [comment]
I think the problem lies here
![image](https://github.com/clauadv/cs2_webradar/assets/23353559/6746b5bf-6dd4-45f5-885f-96d25bd8367c)
handle.second never equals m_id This resulted in an error in line 144
![image](https://github.com/clauadv/cs2_webradar/assets/23353559/6a272664-3e79-4ede-b6bf-131d33c857a8)
