### ISSUE TITLE
How to make teammates have the same color on radar?

### ISSUE THREAD

**Issue by Jonanthandx** [clauadv/cs2_webradar#13]

**Comment by clauadv** [comment]
its basic knowledge but okay..

https://github.com/clauadv/cs2_webradar/blob/main/react/src/Radar/Player.jsx#L35
``backgroundColor: `${playerData.m_team == localTeam && `yellow` || `red`}`,``

**Comment by Jonanthandx** [comment]
Teammates have the same color but different from myself.

**Comment by clauadv** [comment]
you need to change the code
