### ISSUE TITLE
Player Safety and General Concerns: Updates, Security, and Leagues

### ISSUE THREAD

**Issue by MuriloPortoPereira** [clauadv/cs2_webradar#16]
I would like to know about updates, security and Leagues.

Update: it is currently safe to play at MMValve

Security: Could you explain if the .exe moves, edits, reads any game content?

Is it safe to play on Valve's MM? Can it be used in alloys? You can give RED Trust?

**Comment by clauadv** [comment]
its safe to play on matchmaking and yes, it does read the game's memory
