### ISSUE TITLE
Request repair

### ISSUE THREAD

**Issue by MK85Pilot** [clauadv/cs2_webradar#18]
It seems that today's game update has caused some problems, now booting up will output such an error, the map can be recognized on the WEB but there is no information
http://127.0.0.1:5173/data/de_inferno/data.json
{
	"x": -2087,
	"y": 3870,
	"scale": 4.9 
}

[schema.hpp:121] failed to find offset for field 'centityinstance->m_pentity' with hash '1946640611048079800'
[schema.hpp:121] failed to find offset for field 'centityidentity->m_designername' with hash '2475503509145029706'
[schema.hpp:121] failed to find offset for field 'centityinstance->m_pentity' with hash '1946640611048079800'
[schema.hpp:121] failed to find offset for field 'centityidentity->m_designername' with hash '2475503509145029706'
[schema.hpp:121] failed to find offset for field 'centityinstance->m_pentity' with hash '1946640611048079800'
[schema.hpp:121] failed to find offset for field 'centityidentity->m_designername' with hash '2475503509145029706'
[schema.hpp:121] failed to find offset for field 'centityinstance->m_pentity' with hash '1946640611048079800'
[schema.hpp:121] failed to find offset for field 'centityidentity->m_designername' with hash '2475503509145029706'
......

**Comment by clauadv** [comment]
[fixed](https://github.com/clauadv/cs2_webradar/commit/3fbf53510a042ec49f7829d1b72c0b25a8b68828)
