### ISSUE TITLE
Large Delay

### ISSUE THREAD

**Issue by huntergregal** [clauadv/cs2_webradar#19]
There is quite a delay on the player position updates. Any suggestions to get this delay down?

Is it the websocket relay or maybe the useEffect() hook slowing things down?

**Comment by clauadv** [comment]
can you make a small video? i dont remember having any delay at all

**Comment by huntergregal** [comment]
tbh with you - I converted that back end into DMA reads over an fpga and am tunneling the react frontend over ssh to a public server for sharing. and running on a pi. Also using https and wss for the sockets.  but neither are the delay culprit

but the DMA shouldn't be the issue nor the SSH tunnel - i run another DMA (java based) radar that has no delay at all. same hardware as well

**Comment by clauadv** [comment]
no idea. reading from usermode works fine, i was using a kernel driver to read and that works fine aswell with a 1-5ms max. try to debug

**Comment by huntergregal** [comment]
I think there's too many unnecessary reads happening in the usermode/features->run() loop.

For example: m_global_vars->get() should probably only be called once and set globally.

ill try to trim it down outside my work hours
