### ISSUE TITLE
Not really an issue but feature request

### ISSUE THREAD

**Issue by xenu1** [clauadv/cs2_webradar#2]
Could u put health number under the red dots, as well as icon for your player . Been using with my dma so thanks a lot either way

**Comment by clauadv** [comment]
no, that's why i made the player cards. having numbers or text under or above the dot will look awful on the radar.

**Comment by xenu1** [comment]
> no, that's why i made the player cards. having numbers or text under or above the dot will look awful on the radar.

I see, would it be possible to add diff colors for players that are above / below you. Was curious if the game had this info

**Comment by clauadv** [comment]
i will add something. not colors, but something else that wont look ugly.. maybe an arrow or lower/higher opacity on the dots
