### ISSUE TITLE
Can't attach while using NL

### ISSUE THREAD

**Issue by OldNCP** [clauadv/cs2_webradar#24]
The radar fails to attach to CS2 while NL is injected. Maybe there's a way to fix it

**Comment by BallyJery** [comment]
Maybe you could attach cs2 before nl has been injected

**Comment by OldNCP** [comment]
> Maybe you could attach cs2 before nl has been injected

Nope, I've tried that too. Didn't work. It fails to find CS2 I suppose cuz I get an error that it can't find the game process.

**Comment by BallyJery** [comment]
I think it meant that neverlose protected the game process.

**Comment by Gauxalot** [comment]
you wont be able to do use this with neverlose. their driver wont let you inject anything to the game
