### ISSUE TITLE
Can dma be used, or how to use dma? I have compiled it and successfully used it locally. After running it on the second computer, it will display Connected! Waiting for data from usermode

### ISSUE THREAD

**Issue by SuperLifeown** [clauadv/cs2_webradar#34]
Can dma be used, or how to use dma? I have compiled it and successfully used it locally. After running it on the second computer, it will display Connected! Waiting for data from usermode

**Comment by clauadv** [comment]
it's not made for dma. you can use a library to read the memory through dma if you want to.
