### ISSUE TITLE
how do i change ports?

### ISSUE THREAD

**Issue by 3amfox** [clauadv/cs2_webradar#4]
How to change 5173 port?
also i tried to change 22006 in App.jsx (react/src) and app.js in webserver. But it's not working (also changed in usermode)

**Comment by clauadv** [comment]
you can change 22006 port from [here](https://github.com/clauadv/cs2_webradar/blob/main/react/src/App.jsx#L27-L29) and [here](https://github.com/clauadv/cs2_webradar/blob/main/web_server/app.js#L7).
to change 5173 port, you need to edit `vite.config.js` from `react` project, `server: { host: true, port: 1234 }`
