### ISSUE TITLE
bomb timer

### ISSUE THREAD

**Issue by Jumima67** [clauadv/cs2_webradar#41]
I think the offset for the bomb timer is wrong, or atleast it shows like 900 seconds left on bomb.

**Comment by clauadv** [comment]
works fine on my side. can you tell me what you did?

![zVVONgy](https://github.com/user-attachments/assets/9658b34a-9249-4df1-94bf-78ff6386a8cc)

**Comment by Jumima67** [comment]
I installed v1.2 then started server, i had the dependencies already, and compiled usermode.exe myself but didnt change anything in the code.

**Comment by Jumima67** [comment]
So nothing special

**Comment by Jumima67** [comment]
It says version mismatch tho

**Comment by clauadv** [comment]
might be a bug from globalvars. the version mismatch is cuz cs2 got updated recently but its just a warning

**Comment by Jumima67** [comment]
weird it doenst seem to happen anymore, I just tested it again
