### ISSUE TITLE
i GET ERROR WHEN LAUNCH USERMODE_V1.2.EXE

### ISSUE THREAD

**Issue by CORBENDALLAS111** [clauadv/cs2_webradar#43]
[info] config system initialization completed
 [info] exception handler initialization completed
 [error] [memory.cpp:17] failed to hijack a handle for 'cs2.exe'

**Comment by clauadv** [comment]
i have no idea why it fails. join the discord channel and dm me

**Comment by clauadv** [comment]
temp fix https://github.com/clauadv/cs2_webradar/commit/3a8c40dd668673f3a0aae5f29bd102cba94f2c27
