### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by L1berat1on** [clauadv/cs2_webradar#5]
Hello, I would like to ask, if I want to share my radar with others, do I need to buy a server and then fill in the public IP into the PUBLIC_IP?

**Comment by clauadv** [comment]
why would u buy a server? just use your public ip

**Comment by L1berat1on** [comment]
Are you talking about IPv4 addresses?

**Comment by clauadv** [comment]
public ip -> ipinfo.io
local ip -> cmd, ipconfig, ipv4

**Comment by L1berat1on** [comment]
I see, thank you very much, and have a great day

**Comment by clauadv** [comment]
you welcome
