### ISSUE TITLE
Handle Leak in get_process_id Function

### ISSUE THREAD

**Issue by INKCR0W** [clauadv/cs2_webradar#50]
A small optimization opportunity exists in the `get_process_id` function regarding handle management.

### Current Behavior
The function does not consistently close the snapshot handle created by `CreateToolhelp32Snapshot` when a matching process is found.

### Code Location
Function: [get_process_id](https://github.com/clauadv/cs2_webradar/blob/main/usermode/src/utils/memory.cpp#L26)

### Proposed Change
Close the snapshot handle immediately after finding the target process to prevent potential resource leaks.

### Suggested Implementation
```cpp
std::optional<uint32_t> c_memory::get_process_id(const std::string_view& process_name)
{
   const auto snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
   if (snapshot == INVALID_HANDLE_VALUE)
       return {};

   PROCESSENTRY32 process_entry = { 0 };
   process_entry.dwSize = sizeof(process_entry);

   if (Process32First(snapshot, &process_entry)) 
   {
       do {
           if (std::string_view(process_entry.szExeFile) == process_name) 
           {
               CloseHandle(snapshot); // Immediate handle closure
               return process_entry.th32ProcessID;
           }
       } while (Process32Next(snapshot, &process_entry));
   }

   CloseHandle(snapshot);
   return {};
}

**Comment by clauadv** [comment]
thank you
